# RandomForest Implementation | Classification

In [19]:
#Reading all the packages 
import pandas as pd
import numpy as np
import tensorflow_data_validation as tfdv
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier as rf
from sklearn import datasets

## Reading the data and visualizing

In [28]:
##Reading a dataset of patient with heart disease to build a predictor which can predict heart disease in people

df = pd.read_csv('D:\Github_projects\Classifier- RandomForest/HeartDisease.csv')
print(df.dtypes)
df.head()

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

## EDA using TensorFlow Data Validation

#### Before starting the EDA, let's split the data in training and testing datasets

In [38]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=1)

In [49]:
#creating a complete train dataset for EDA
train_df = pd.concat([X_train, y_train], axis=1)
train_df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
41,54,F,NAP,130,294,0,ST,100,Y,0.0,Flat,1
891,66,F,NAP,146,278,0,LVH,152,N,0.0,Flat,0
265,54,M,ATA,160,305,0,Normal,175,N,0.0,Up,0
177,59,M,ATA,140,287,0,Normal,150,N,0.0,Up,0
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1
...,...,...,...,...,...,...,...,...,...,...,...,...
767,54,F,NAP,108,267,0,LVH,167,N,0.0,Up,0
72,52,M,ASY,120,182,0,Normal,150,N,0.0,Flat,1
908,63,M,ASY,140,187,0,LVH,144,Y,4.0,Up,1
235,39,M,ATA,120,200,0,Normal,160,Y,1.0,Flat,0
37,41,F,ATA,110,250,0,ST,142,N,0.0,Up,0

#### Beginning EDA in TFDV

In [54]:
train_stats = tfdv.generate_statistics_from_dataframe(train_df)
tfdv.visualize_statistics(train_stats)

In [55]:
schema = tfdv.infer_schema(statistics=train_stats)
tfdv.display_schema(schema=schema)

                    Type  Presence Valency            Domain
Feature name
'Age'                INT  required                         -
'Sex'             STRING  required                     'Sex'
'ChestPainType'   STRING  required           'ChestPainType'
'RestingBP'          INT  required                         -
'Cholesterol'        INT  required                         -
'FastingBS'          INT  required                         -
'RestingECG'      STRING  required              'RestingECG'
'MaxHR'              INT  required                         -
'ExerciseAngina'  STRING  required          'ExerciseAngina'
'Oldpeak'          FLOAT  required                         -
'ST_Slope'        STRING  required                'ST_Slope'
'HeartDisease'       INT  required                         -

                                     Values
Domain
'Sex'                              'F', 'M'
'ChestPainType'   'ASY', 'ATA', 'NAP', 'TA'
'RestingECG'          'LVH', 'Normal', 'ST'
'ExerciseAngina'                   'N', 'Y'
'ST_Slope'             'Down', 'Flat', 'Up'

## Data Transformations

## Building the model

## Predicting the output

## Accuracy Check